config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :posts

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index]
      get '/posts/:slug', to: 'posts#show', as: 'post'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homepage#index"
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  field :slug, type: String
  field :title, type: String
  field :body, type: String
  field :author, type: String, default: ""

  validates :title, presence: true
  validates :slug, presence: true
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      rescue_from Mongoid::Errors::DocumentNotFound, with: :record_not_found
      rescue_from Error::CustomServerError, with: :server_error
      
      def index
        @posts = ::Post.all
      end

      def show
        raise Error::CustomServerError if params[:slug] == 'raise-500'
        @post = ::Post.find_by(slug: params[:slug])
      end

      private
      def record_not_found(error)
        render(json: {message: "no record found"}, status: :not_found)
      end

      def server_error(error)
        render(json: {message: "server error"}, status: :internal_server_error)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :author, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homepage/index.html.haml
%h1#title Cypress rails demo
%p.main-body There should be a spec looking for the word demo

= link_to "View Posts", posts_path, class: "button"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CypressIoRailsDemo | <%= content_for?(:title) ? yield(:title) : "Homepage" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .field.title
    = f.label :title
    = f.text_field :title
  .field.body
    = f.label :body
    = f.text_field :body
  .field.author
    = f.label :author
    = f.text_field :author
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h2= link_to("Home Page", root_path)

%h1.title Listing posts

%table
  %thead
    %tr
      %th Title
      %th Body
      %th Author
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.body
        %td= post.author
        %td= link_to 'Show', post_path(post)

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Body:
  = @post.body
%p
  %b Author:
  = @post.author

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path